### ISSUE TITLE
PHP Notice:  Undefined variable: string in /path/to/app/vendor/querypath/querypath/src/QueryPath.php on line 240

### ISSUE THREAD

**Issue by sandeepshetty** [technosophos/querypath#147]
`$string` here is undefined. https://github.com/technosophos/querypath/blob/59fd8d48c9cc717cf21034079e69569e5577865b/src/QueryPath.php#L240

Plus, the `if` and the `else` there are both doing the same thing?!

```php
      if (strpos($string, '<') !== FALSE && strpos($string, '>') !== FALSE) {
        $source = $html5->loadHTML($source);
      }
      else {
        $source = $html5->loadHTML($source);
      }
```

What gives?

**Comment by technosophos** [comment]
I merged #148, so I am closing this.
