### ISSUE TITLE
qr() function returns \QueryPath\DOMQuery, not QueryPath

### ISSUE THREAD

**Issue by Sarke** [technosophos/querypath#150]
It's messing with the auto-completion, and is in general incorrect.

qp_functions.php, line 149

    * @return QueryPath

should be 

    * @return \QueryPath\DOMQuery

as that is what QueryPath::with() returns.

Thanks,
Peter

**Comment by technosophos** [comment]
You're right. The docs for that file were not correctly updated when we released 3.x. I'll fix.
