### ISSUE TITLE
unwrap elements

### ISSUE THREAD

**Issue by lramarojaona** [technosophos/querypath#153]
Hi,

I've been struggling with that for few hours now and I would like to find a clean way to do following:

Let's say I have following HTML structure:
```html
<body>
<div class="classname">
  <h2>
    <em>A nice title</em>
  </h2>
  <h3>A subtitle</h3>
  <ul>
    <li>Item 01</li>
    <li>Item 02 </li>
  </ul>
</div>
</body>
```
Right now I'm using
```php
$qp = htmlqp($html, '.classname');
```

And I would like to have the following result:
```html
  <h2>
    <em>A nice title</em>
  </h2>
  <h3>A subtitle</h3>
  <ul>
    <li>Item 01</li>
    <li>Item 02 </li>
  </ul>
```

I tried with unwrap(), but it doesn't do what I want.

Any help would be greatly appreciated! :)

Thanks!

**Comment by technosophos** [comment]
Would `htmlqp($html, '.classname >')->unwrap()` work? That should unwrap all the children inside of `.classname`.

Otherwise, you might do:

```php
$qp = htmlqp($html, '.classname');
$children = $qp->removeChildren();
$qp->after($children);
```
That would move the children up a level. I guess you'd still have to delete the div element, too, in that case.

**Comment by lramarojaona** [comment]
Using
```php
htmlqp($html, '.classname >')->unwrap();
```
throws followin error:
`
Error: Call to undefined method DOMDocument::hasAttribute() in querypath/src/QueryPath/CSS/DOMTraverser.php, line 682
`

The second method you suggest doesn't result in the desired output.
```php
$qp = htmlqp($html, '.classname');
$children = $qp->removeChildren();
$qp->after($children);
print $qp->html();
```
outputs this:
```html
<div class="victims"></div>
```

**Comment by technosophos** [comment]
Victims! That sounds scary!

The first part sounds like a bug in QueryPath. It should not throw an error like that.

For the second one, what is the contents of `$children`? Maybe it's not returning the list of children correctly.

**Comment by lramarojaona** [comment]
Yeah sorry, I forgot to anonymize the code :)

1. I was assuming that QueryPath couldn't handle such a selector, but if it's a bug, then it should be fixable. I cannot help on that however.

2. if I do `print $children->html()` I only get the victim thing:
```html
<div class="victims"></div>
```

**Comment by lramarojaona** [comment]
So what do you think?
Is there a work-around or is this a bug?

Thanks!

**Comment by technosophos** [comment]
How about this?

```php
$html = '<html><body>
<div class="classname">
  <h2>
    <em>A nice title</em>
  </h2>
  <h3>A subtitle</h3>
  <ul>
    <li>Item 01</li>
    <li>Item 02 </li>
  </ul>
</div>
</body></html';

// The outer wrapper
$qp = htmlqp($html, '.classname');
// Get the children that we want to move.
$kids = $qp->children();
// Find the place we want to put the children.
$destination = $qp->parent();

// Move the children to that place.
foreach ($kids as $child) {
  $destination->append($child);
}

// Get rid of the one we don't want anymore.
$qp->remove();

echo $qp->top()->html();
```
It's a little more verbose, but it does what (I think) you want.

**Comment by lramarojaona** [comment]
Thank you for the help, I'm getting close, but I still have to get rid of the body that wraps all elements.

```php
$html = '<div class="classname">
  <h2>
    <em>A nice title</em>
  </h2>
  <h3>A subtitle</h3>
  <ul>
    <li>Item 01</li>
    <li>Item 02 </li>
  </ul>
</div>';

// The outer wrapper
$qp = htmlqp($html, '.classname');

// Get the children that we want to move.
$kids = $qp->children();
// Find the place we want to put the children.
$destination = $qp->parent();

// Move the children to that place.
foreach ($kids as $child) {
  $destination->append($child);
}

// Get rid of the one we don't want anymore.
$qp->remove();

// This returns <body><h2><em>A nicd-e title</em></h2>...
print $destination->html();
```

Which leads to the same situation where I have to unwrap... :(

**Comment by lramarojaona** [comment]
I got it.

By using
```php
print $destination->html();
```

Thank you! :+1:

**Comment by lramarojaona** [comment]
Well, I think I closed the issue too fast.
What I should return is a QueryPath object and not an HTML string.

Any idea?

**Comment by lramarojaona** [comment]
I found the solution, just by add ing children() function:

```php
$qp = htmlqp($html, '.classname')->children();
```

This will produce **several results**, not one unique result that contains all HTML code.
