### ISSUE TITLE
ム breaks querypath

### ISSUE THREAD

**Issue by natostanco** [technosophos/querypath#159]
I have this character "ム" popping up in a query, and it just makes querypath return null, I have isolated   from a string and it is the only character that makes the query return null, just by removing it the query works, I suspect there are some other characters like this that break qp...why is that?...This seem to be standard utf-8, and all the other utf-8 chars (in the query) work ok...

**Comment by natostanco** [comment]
query uses :contains pseudo class, I would say utf8 is not supported in the text specified by :contains

**Comment by technosophos** [comment]
While it's odd that that one character fails, I think you are probably right. There's probably a UTF-8 issue in the logic for contains.

Out of curiosity, will that load fine using just html5-php?

**Comment by eclipxe13** [comment]
I can't replicate the error, I'm using this code:
```
    <?php
    require 'vendor/autoload.php';
    use Masterminds\HTML5;

    $html5 = new HTML5();
    $dom_results = $html5->loadHTML('<div>イスラム国 動画</div>');
    foreach(['イ', 'ム' , '動'] as $x) {
        $query_results = qp($dom_results, 'div:contains(' . $x . ')')->html();
        echo $x, print_r($query_results, true), "\n";
    }
```
And get the following result:
```
イ<div>イスラム国 動画</div>
ム<div>イスラム国 動画</div>
動<div>イスラム国 動画</div>
```
The file is UTF-8 and the runtime is UTF-8 also. PHP Version 5.6.9-1, masterminds/html5 2.1.1, querypath/querypath 3.0.3

**Comment by technosophos** [comment]
I wonder if this has to do with the version of the mb_* library that ships with PHP. That's what QueryPath uses for handling encodings.

http://php.net/manual/en/book.mbstring.php

**Comment by eclipxe13** [comment]
Well, I have mbstring extension built in, but no configuration:
```
$ php -r 'phpinfo();' | grep -i mbstring
Zend Multibyte Support => provided by mbstring
mbstring
mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.
mbstring.detect_order => no value => no value
mbstring.encoding_translation => Off => Off
mbstring.func_overload => 0 => 0
mbstring.http_input => no value => no value
mbstring.http_output => no value => no value
mbstring.http_output_conv_mimetypes => ^(text/|application/xhtml\+xml) => ^(text/|application/xhtml\+xml)
mbstring.internal_encoding => no value => no value
mbstring.language => neutral => neutral
mbstring.strict_detection => Off => Off
mbstring.substitute_character => no value => no value
```
