### ISSUE TITLE
Need ability to set user agent

### ISSUE THREAD

**Issue by doapp-ryanp** [technosophos/querypath#161]
When making call to `html5qp()` I need the ability to set the user agent that `Masterminds\HTML5` will use when doing the HTTP GET.

**Comment by technosophos** [comment]
IIRC, QueryPath uses stream wrappers to get the URL. QueryPath can pass a stream context,  which allows you to set a number of HTTP-specific parameters.

Take a look at this example to see how it works:
https://github.com/technosophos/querypath/blob/fea10b59f10bd45ff7d5cfd7c86851d1bfd0df1c/examples/dbpedia.php#L53
