### ISSUE TITLE
Class '\\QueryPath\\DOMQuery' not found in QueryPath/QueryPath.php

### ISSUE THREAD

**Issue by turboflash** [technosophos/querypath#164]
I hit into the subject error and I did some quick investigation on why it occurs. It seems the issue happens in the autoload code below. 

```php
    spl_autoload_register(function ($klass) {
      $parts = explode('\\', $klass);
      file_put_contents('/tmp/output.log', var_export(array($klass, $parts), true), FILE_APPEND);
      if ($parts[0] == 'QueryPath') {
        $path = __DIR__ . '/' . implode('/', $parts) . '.php';
        if (file_exists($path)) {
          require $path;
        }
      }
    });
```

`$klass` was assigned `'\QueryPath\DOMQuery'` when the function is called. After exploding `$klass` into `$parts`, the following is the resulting array. `require $path` would not be executed as `$parts[0]` is not equal to `'QueryPath'`.

```php
  array (
    0 => '',
    1 => 'QueryPath',
    2 => 'DOMQuery',
  )
```

**Comment by technosophos** [comment]
So I'm thinking just doing something like this:

```php
if ($parts[0] == '') {
  array_shift($parts)
}
```
That would fix the use case, and hopefully stay backward compatible. See any issues with that?

**Comment by turboflash** [comment]
Nope. That resolves the issue. ;)
