### ISSUE TITLE
querypath returns only one item instead of several ones

### ISSUE THREAD

**Issue by gordielachance** [technosophos/querypath#165]
Hi,

I got this string (see below); which is an XML but that I did load as an HTML (because I need it).
When doing

    $track_node->find('pictures:eq(2)');

It doesn't return anything.  Seems it doesn't allow multiple pictures tags.

    $track_node->find('pictures'); 

works (and return the first item).

Can anyone explain me why; and eventually how I could fix this ?

Thanks !

    <tracks>
    <id>86bb64891c88a25c3c5a9d9d60e0de09</id>
    <type>general</type>
    <artist>Russ Gabriel</artist>
    <title>Trip Do Brasil - Jelba</title>
    <duration>560</duration>
    <timetoplay>253</timetoplay>
    <pictures>http://www.ledjamradio.com/ressources/images/tracks/background-2147aa8aead56dfeb0875d5a4ecf8c53.jpg</pictures>
    <pictures>http://farm4.static.flickr.com/3001/3002879633_822b1df6a4.jpg</pictures>
    <pictures>http://m.c.lnkd.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAFiAAAAJGJlZjhmYTJhLWUxZjQtNDZhNC1hZWFmLTUxYjQyMTM4MDBjMw.jpg</pictures>
    <pictures>http://farm5.static.flickr.com/4084/5025695142_cabe63c557_o.jpg</pictures>
    <pictures>http://a2.ec-images.myspacecdn.com/profile01/141/650350c549ef4d1dba6d9ea5586fc4f8/p.jpg</pictures>
    <pictures>http://userserve-ak.last.fm/serve/_/59614375/Russ+Gabriel.jpg</pictures>
    <pictures>http://upload.wikimedia.org/wikipedia/commons/3/3f/Aroutcheff.jpg</pictures>
    <pictures>http://www.freecodesource.com/album-cover/41iQuvEEebL/Bjorn-Torske,-Russ-Gabriel,-Stasis,-Aubrey,-Max-Brennan,-4th-Wave-Vs.-Synchrojack,-Dan-Curtin-&-Mike-Filly,-The-Invisibles,-Idiot-Savant,-Fusion,-Ian-O'Brien-Carl-Craig-Further-Adventures-in-Techno-Soul.jpg</pictures>
    <pictures>http://userserve-ak.last.fm/serve/_/2162386.jpg</pictures>
    <pictures>http://i2.ytimg.com/li/TKIrQaRynSk/hqdefault.jpg</pictures>
    <spotify>
        <id>spotify:track:3ylfRoZZwkQSREtZ472HcM</id>
        <url>https://play.spotify.com/track/3ylfRoZZwkQSREtZ472HcM</url>
    </spotify>
    <deezer>
        <id>78483927</id>
        <url>http://www.deezer.com/track/78483927?app_id=126395</url>
    </deezer>
    <edito>Russ Gabriel almost certainly needs no introduction: since 1993, he and his Ferox label have helped define the sound of UK techno, merging elements from Detroit and Chicago into a sound that stands confidently on its own. Russ had been quiet for a few years, until last year he announced the return of Ferox. Now he will release a two tracker on Mobilee with a record that confirms his reputation as one of electronic music's true, enduring greats. Recognizing that power isn't all about brute force, both cuts hypnotize and seduce with elegant constructions and slowly shifting modulations. Read more about Russ Gabriel on Last.fm.</edito>
    <trackpoints>1404</trackpoints>
    <artistpoints>0</artistpoints>
    <votable>1</votable>
</tracks>

**Comment by technosophos** [comment]
What's the result of doing something like this?
```php
echo qp($xml, 'pictures')->count();
```
or
```php
echo qp($xml)->find('pictures')->eq(2)->text();
```

**Comment by gordielachance** [comment]
$track_node->find('pictures')->count()

return 10 (this is great)

    $track_node->find('pictures')->eq(2)->text();

works as expected,

    $track_node->find('pictures:first')->text();
    $track_node->find('pictures:eq(2)')->text();

Do not work.
...and I need to find it using a string selector... :/

**Comment by technosophos** [comment]
Okay, so here's an annoying thing about CSS3: what you actually want is `:first-of-type` and `nth-of-type(2)`. The CSS3 spec defined these differently than jQuery used them, so `pictures:eq(2)` actually returns you the 2nd element under tracks, but only if it's a `pictures` element (which it's not).

You can see this in action by using the filter `pictures:eq(7)` (which returns what you'd expect from `pictures:eq(1)`.)
