### ISSUE TITLE
Issue try to get attribute

### ISSUE THREAD

**Issue by gordielachance** [technosophos/querypath#167]
Hi !
Loading this document : http://spinb.in/npr---songs-we-love.xspf, I can't get the **xmlns** attribute of the playlist node.  It is strange because I CAN get the version attribute.  Any idea ?

    $playlist = $feed_body_node->find('playlist');
    var_dump($playlist->attr('version')); //string(1) "1"
    var_dump($playlist->attr('xmlns')); //string(0) ""

Any idea about this ?
Thanks !

**Comment by technosophos** [comment]
Oh, the joys of XML. For some reason, the XML parser does not add xmlns into the list of attributes. Instead, it puts this on the DOM node as $namespaceURI. So you have to get the document element and access the attribute (`echo qp->get(0)->namespaceURI`).

Nobody's ever really asked me about using this, but I'm wondering if it would be convenient to have a `namespace()` or `ns()` function that gives the namespace of the currently selected element. That way you could do `qp()->ns()` and get the namespace string. Think that'd be a useful feature?

**Comment by cognifloyd** [comment]
ns() is a good idea. +1
