### ISSUE TITLE
Trouble using library. Support request. Should be quick. Please help.

### ISSUE THREAD

**Issue by nickolasnikolic** [technosophos/querypath#170]
I have this line that isn't working:

echo qp( $formattedResponse, 'purchaseurl' )->text();

And it pulls from this document:

<-?xml version="1.0" encoding="UTF-8"?->
<--cartcreateresponse xmlns="http://webservices.amazon.com/AWSECommerceService/2011-08-01"-->
   <-operationrequest->
      <-httpheaders->
         <-header name="UserAgent" value="ApaiIO [2.0.0-DEV]" /->
      <-/httpheaders->
      <-requestid->1DRADG4SGKV2WEDBCG53<-/requestid->
      <-arguments->
         <-argument name="Service" value="AWSECommerceService" /->
         <-argument name="Item.1.Quantity" value="1" /->
         <-argument name="Item.3.Quantity" value="1" /->
         <-argument name="Operation" value="CartCreate" /->
         <-argument name="Item.5.Quantity" value="1" /->
         <-argument name="Timestamp" value="2015-07-23T14:51:03Z" /->
         <-argument name="Version" value="2011-08-01" /->
         <-argument name="AssociateTag" value="blindworm-20" /->
         <-argument name="Item.4.Quantity" value="1" /->
         <-argument name="Item.1.ASIN" value="1452102988" /->
         <-argument name="Item.4.ASIN" value="B010K4MUBM" /->
         <-argument name="Signature" value="m70A7hXGsGhyes/mMPOSlVktXGaZoO61G3MST94weq8=" /->
         <-argument name="Item.2.ASIN" value="080241270X" /->
         <-argument name="Item.2.Quantity" value="1" /->
         <-argument name="Item.5.ASIN" value="B004XWPYMU" /->
      <-/arguments->
      <-requestprocessingtime->0.133409976959229<-/requestprocessingtime->
   <-/operationrequest->
   <-cart->
      <-request->
         <-isvalid->True<-/isvalid->
         <-cartcreaterequest->
            <-items->
               <-item->
                  <-asin->1452102988<-/asin->
                  <-quantity->1<-/quantity->
               <-/item->
               <-item->
                  <-asin->080241270X<-/asin->
                  <-quantity->1<-/quantity->
               <-/item->
               <-item->
                  <-asin->1937006883<-/asin->
                  <-quantity->1<-/quantity->
               <-/item->
               <-item->
                  <-asin->B010K4MUBM<-/asin->
                  <-quantity->1<-/quantity->
               <-/item->
               <-item->
                  <-asin->B004XWPYMU<-/asin->
                  <-quantity->1<-/quantity->
               <-/item->
            <-/items->
         <-/cartcreaterequest->
      <-/request->
      <-cartid->183-2974980-0109268<-/cartid->
      <-hmac->g1tm8HiuxH7ymFrqaKF5ILCrcvE=<-/hmac->
      <-urlencodedhmac->g1tm8HiuxH7ymFrqaKF5ILCrcvE%3D<-/urlencodedhmac->
      <-purchaseurl->https://www.amazon.com/gp/cart/aws-merge.html?cart-id=183-2974980-0109268%26associate-id=blindworm-20<-/purchaseurl->
      <-subtotal->
         <-amount->2140<-/amount->
         <-currencycode->USD<-/currencycode->
         <-formattedprice->$21.40<-/formattedprice->
      <-/subtotal->
      <-cartitems->
         <-subtotal->
            <-amount->2140<-/amount->
            <-currencycode->USD<-/currencycode->
            <-formattedprice->$21.40<-/formattedprice->
         <-/subtotal->
         <-cartitem->
            <-cartitemid->C13XEXT5Y4Y8R<-/cartitemid->
            <-asin->1452102988<-/asin->
            <-sellernickname->Amazon.com<-/sellernickname->
            <-quantity->1<-/quantity->
            <-title->Me without You<-/title->
            <-productgroup->Book<-/productgroup->
            <-price->
               <-amount->590<-/amount->
               <-currencycode->USD<-/currencycode->
               <-formattedprice->$5.90<-/formattedprice->
            <-/price->
            <-itemtotal->
               <-amount->590<-/amount->
               <-currencycode->USD<-/currencycode->
               <-formattedprice->$5.90<-/formattedprice->
            <-/itemtotal->
         <-/cartitem->
         <-cartitem->
            <-cartitemid->C3M2X8EJL5FWH3<-/cartitemid->
            <-asin->080241270X<-/asin->
            <-sellernickname->Amazon.com<-/sellernickname->
            <-quantity->1<-/quantity->
            <-title->The 5 Love Languages: The Secret to Love that Lasts<-/title->
            <-productgroup->Book<-/productgroup->
            <-price->
               <-amount->883<-/amount->
               <-currencycode->USD<-/currencycode->
               <-formattedprice->$8.83<-/formattedprice->
            <-/price->
            <-itemtotal->
               <-amount->883<-/amount->
               <-currencycode->USD<-/currencycode->
               <-formattedprice->$8.83<-/formattedprice->
            <-/itemtotal->
         <-/cartitem->
         <-cartitem->
            <-cartitemid->C114ZAXHTN8CHX<-/cartitemid->
            <-asin->1937006883<-/asin->
            <-sellernickname->Amazon.com<-/sellernickname->
            <-quantity->1<-/quantity->
            <-title->How to Love (Mindful Essentials)<-/title->
            <-productgroup->Book<-/productgroup->
            <-price->
               <-amount->667<-/amount->
               <-currencycode->USD<-/currencycode->
               <-formattedprice->$6.67<-/formattedprice->
            <-/price->
            <-itemtotal->
               <-amount->667<-/amount->
               <-currencycode->USD<-/currencycode->
               <-formattedprice->$6.67<-/formattedprice->
            <-/itemtotal->
         <-/cartitem->
      <-/cartitems->
   <-/cart->
<-/cartcreateresponse->

**Comment by technosophos** [comment]
What is it actually echoing? Too much data? Nothing? The wrong data?

**Comment by technosophos** [comment]
Also, I'm not too familiar with all of amazon's APIs, but I have seen that they mix cases in element names sometimes. QueryPath tag matching is case sensitive. So if the element is actually PurchaseURL, QP won't find it.

**Comment by nickolasnikolic** [comment]
nothing, is it case sensitive, by the way?

**Comment by nickolasnikolic** [comment]
That solves it: case sensitivity. Thank you!

**Comment by nickolasnikolic** [comment]
That was it. Thanks! -nn
