### ISSUE TITLE
Ignores the nested UL

### ISSUE THREAD

**Issue by 3zzy** [technosophos/querypath#171]
HTML:

    <ul class="tree">
        <li class="parent store first"> <a data-layout="newLayout" class="parent current active">
                <span class="arrow"> </span>
                Mobiles & Accessories
            </a>
    
            <ul>
                <li class="store"> <a data-layout="newLayout" href="/mobiles/pr?sid=tyy,4io&q=iphone+5s" path="mobiles" sid="tyy,4io" type="" class="active">
                        Mobiles
                        <span class="count">(12)</span>
                    </a>
    
                </li>
                <li class="store"> <a data-layout="newLayout" path="tablets" sid="tyy,hry" type="" class="grayed">
                        Tablets
                        <span class="count">(0)</span>
                    </a>
    
                </li>
                <li class="store"> <a data-layout="newLayout" href="/mobile-accessories/pr?sid=tyy,4mr&q=iphone+5s" path="mobile-accessories" sid="tyy,4mr" type="" class="active">
                        Mobile Accessories
                        <span class="count">(131,490)</span>
                    </a>
    
                </li>
                <li class="store"> <a data-layout="newLayout" href="/tablet-accessories/pr?sid=tyy,jgu&q=iphone+5s" path="tablet-accessories" sid="tyy,jgu" type="" class="active">
                        Tablet Accessories
                        <span class="count">(453)</span>
                    </a>
    
                </li>
                <li class="store"> <a data-layout="newLayout" path="landline-phones" sid="tyy,n0e" type="" class="grayed">
                        Landline Phones
                        <span class="count">(0)</span>
                    </a>
    
                </li>
            </ul>
        </li>
    </ul>

PHP:

    foreach ($qp->find('.tree a[data-layout="newLayout"]') as $cat) {
        echo print_r($cat->text(),1) . "\n";
    }

.. unexpectedly returns only:

                              Mobiles & Accessories
                        
    
     Landline Phones
                   

**UPDATE**: Looks like its a bug actually cause it just doesn't detect the `ul`:

    $qp->find('.tree')->html();

Returns:

    <ul class="tree">
        <li class="parent store active first">
            <a data-layout="" href="" path="mobiles-accessories" sid="tyy" type="products" class="parent active">
                <span class="arrow"> </span> Mobiles &amp; Accessories
            </a>
            <ul class="tree">
                <li class="parent store ">
                    <a data-layout="newLayout" class="parent current active">
                        Landline Phones
                    </a>
                </li>
            </ul>
        </li>
    </ul>

**Comment by 3zzy** [comment]
Please delete, I was comparing apple and orange. ;)

**Comment by technosophos** [comment]
Okay. Considering this closed.
