### ISSUE TITLE
Typo in last release version.

### ISSUE THREAD

**Issue by limonte** [technosophos/querypath#175]
Dot is missing in latest version:

![](https://i.imgur.com/tTRSLTN.png)

**Comment by technosophos** [comment]
Thank you for pointing that out. I fixed it by adding a new tag, but following the recommended practice of not deleting the old one.

**Comment by limonte** [comment]
@technosophos I'm using [sllh/composer-versions-check](https://github.com/Soullivaneuh/composer-versions-check) to automatically check deps for updates. Unfortunately even after creating v3.0.4 that plugin suggests me v3.04 as newest:

```
$ composer update
...
Some packages are not up to date:

  - querypath/querypath (3.0.4) last version is 3.04
```

I'm not sure on which side this issue shoul be fixed. Any thoughts?

**Comment by limonte** [comment]
@Soullivaneuh please take a look on this unusual case, your opinion will be very useful here.

**Comment by limonte** [comment]
@isaacs may be you can give any suggestion here, thanks :)

**Comment by isaacs** [comment]
I have no connection to composer/packagist/etc., sorry.  Left PHP for JavaScript many years ago.

**Comment by technosophos** [comment]
I've got a 3.0.5 release coming down soon.

I looked at deleting the tag, but the official Git documentation suggests this is a bad idea. (There's even a sample apology email for me to send, since I screwed up everyone's tags.)

Sorry for this inconvenience.
Matt

**Comment by Soullivaneuh** [comment]
@limonte I'm using [`composer/semver`](https://github.com/composer/semver) for version compare.

IMO, `3.04` is treated like `3.4` that is superior to `3.0`.

Until a real `3.4` version will be out, you will still have this issue.

@technosophos For git tags and composer, I already removed a buggy tag from both of them without any issue. BTW, tag name are not the same so you should not have so much trouble AFAIK.

**Comment by Soullivaneuh** [comment]
BTW @technosophos You will have the same issue here: https://packagist.org/packages/querypath/querypath#3.04

`3.04`, treated like `3.4` may be always on top, considered as the last version. This would be confusing for your users.

**Comment by technosophos** [comment]
Marking re-opened. I will get the tag deleted.

**Comment by limonte** [comment]
@technosophos can you please delete mistaken tag?

**Comment by technosophos** [comment]
Done
