### ISSUE TITLE
Call to undefined method Masterminds\HTML5::loadFragment() in DomQuery::html5() 

### ISSUE THREAD

**Issue by ZhangYiJiang** [technosophos/querypath#182]
To repro: 

```
>>> $dom = html5qp('<div></div>') 
>>> $dom->find('div')->html5('<p>Hello world</p>')
                                                              
     Call to undefined method Masterminds\HTML5::loadFragment()  
```

The error comes from `DomQuery.php` on Line 2344: 

          $doc = $html5->loadFragment($markup);

The problem is this function `loadFragment` doesn't appear to exist. This is causing all calls to `DomQuery::html5()` with the first parameter to fail. I'm not sure if it used to exist at some point in the `Masterminds\HTML5` library, but it doesn't in the current version required via composer by querypath. There is a function called `loadHTMLFragment` in the `HTML5` class, but I don't know if this is what is needed here. I did patch my local development copy of the file with this change and it does seem to work fine. I can make that change and drop a pull request if you want.

**Comment by ZhangYiJiang** [comment]
A workaround that doesn't require patching the vendor files is to do 

```
$element->removeChildren();
$element->append(html5qp('<p>My new HTML</p>'));
```

This is not ideal, but it seems to do the same thing as the `html5` setter function.

**Comment by letapjar** [comment]
I got this to work by changing the line to:  loadHTMLFragment($markup)   
would be good if someone could confirm this though.

**Comment by ZhangYiJiang** [comment]
Yes, that works, but you're patching a vendor file which is problematic because the changes you make will be wiped out by composer the next time this package updates
